id: A7788255F
title: Extemporary Practice of Longevity for Oneself or Others
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.946317
  last_modified_at: 2022-03-01 04:28:26.946320
