id: A7788255F
title: The Dhāraṇī of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.949299
  last_modified_at: 2022-03-01 04:28:26.949302
