id: A7788255F
title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
  Practice that Unites the Oral, Treasure and Visionary Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.952794
  last_modified_at: 2022-03-01 04:28:26.952797
