id: A7788255F
title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret Pith
  Instructions on Attaining Vajra Longevity'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.951495
  last_modified_at: 2022-03-01 04:28:26.951498
