id: A7788255F
title: The Sūtra of Boundless Life and Wisdom
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.955708
  last_modified_at: 2022-03-01 04:28:26.955711
