id: A7788255F
title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the Three
  Deities of Long Life'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.944969
  last_modified_at: 2022-03-01 04:28:26.944974
