id: A7788255F
title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas, from
  the Heart Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:28:26.957700
  last_modified_at: 2022-03-01 04:28:26.957703
